
## Downloading Ichthyop {#sec-osm-inst}

The Ichthyop tool is available on [GitHub](https://github.com/ichthyop/ichthyop). There are two ways to use Ichthyop:

- Use executable files (`.jar` files) (**preferably for beginners**)
- Use source files (**preferably for advanced users and developers**)

### Using executable files

Ichthyop executable files can be downloaded [here](https://github.com/ichthyop/ichthyop/releases). Download the  latest `ichthyop-X.Y.Z-jar-with-dependencies.jar` file (replacing `X.Y.Z` by the version number). Older versions are also available if necessary.

### From source

To get the source code, type in a Terminal (Unix/MacOs) or Git Bash prompt (Windows):

```bash
git clone https://github.com/ichthyop/ichthyop.git
```

The code can then be compiled either using IDE (NetBeans, VSCode) or using the following command line:

```bash
mvn package
```

The executable will be generated in the `target` folder.

:::{.callout-warning}
To use the command line, Maven needs to be installed (see instructions on <https://maven.apache.org/install.html>)
:::
