## Prerequisites

### Java

In order to run Ichthyop, **Java (>= 11)**  needs to be installed. To make sure that Java is installed and that you have the right version,
type:

```bash
java --version
```

If you see an error, then you need to install Java. If the version is less than 11, you need to reinstall it.

If needed, see @sec-java-install for the Java install instructions.

### NetCDF4

The Java library that manages input/output of
files in Ichthyop requires the external NetCDF C library, which can be installed as follows:

#### Mac Os X

Open a Terminal and type:

```bash
sudo port install netcdf4
```

#### Linux

Open a Terminal and type:

```bash
sudo apt-get install netcdf4
```

#### Windows

Download the pre-built libraries from
[Unidata website](https://docs.unidata.ucar.edu/netcdf-c/current/winbin.html)

:::{.callout-caution}
During the install process, make sure that the location of the library is added to
the `PATH`
:::

### Conda environmenmt

There is also the possibility to use Conda environments in order to install Maven, OpenJDK and NetCDF4 easily. Instructions can be found on <https://github.com/ichthyop/ichthyop-conda>
