### Buoyancy

A buoyancy module allows to  displace a particle vertically, depending on it's density and  the sea water density, following @parada2003modelling.

The buoyancy-induced vertical velocity of the particle is given by:

$$
W_{buoy} =  \dfrac{1}{24} \times g \times  a \times  b  \times \dfrac{\rho_{water} - \rho_{part}}{\rho_{water}} \mu^{-1} \log\left(2 \dfrac{a}{b} + 0.5\right);
$$

with $a$ and $b$ the semi-major axis and semi-minor axis of an ellipse (`mean_major_axis` and `mean_minor_axis` parameters), $\mu$ the molecular viscosity (`molecular_viscosity` parameter), $\rho_{water}$ the water density, $\rho_{part}$ the particle density and $g$ the gravitational acceleration ($cm.s^{-2}$).

There are two possibilities to define the particle buoyancy, which are provided by the `density.method` parameter:

- If `constant`, then a constant density (in $g.cm^{-3}$) is used, which is provided by the `particle_density` parameter.
- If `file`, then the buoyancy is read from a file and can vary with either age or length. The class that is used is provided by the `density.class` parameter.

The density CSV file must be formatted in the following way:

```bash
Age(Days);Density (g/cm3)
0;1.0235625
1;1.02374
2;1.023335
2.5;1.0239
2.75;1.025672
```

Sea-water density is computed using sea-water temperature and salinity following @MILLERO1981625 and the technical implementation described in @fofonoff1983algorithms (EOS-80). Using the polynomials values from @MILLERO1981625, the density anomalie $\Delta \sigma = \sigma - \sigma_0$, with $\sigma_0 = \sigma(S=35, T=0, P=0)$, is computed. Density is then computed as:

$$
\rho = \sigma_0 + \Delta \sigma + \rho_0
$$

with $rho_0 = 1000 kg.m^{m-3}$ the reference density of water. Finally, density is converted into $g.cm^{-3}$.