#### DEB growth

::: {.callout-caution}

The documentation for the DEB module is still ongoing

:::

The DEB equations are based on @kooijman2010dynamic, @KOOIJMAN2011, @KOOIJMAN2014 and can be found in @FLORESVALIENTE2023103034

Influence of temperature is given by equation 5 of @FLORESVALIENTE2023103034:

$$
c_T = \exp \left( \dfrac{T_A}{T_1} - \dfrac{T_A}{T} \right)
\left[
\dfrac{
1 +
\exp
\left(
\dfrac{T_{AL}}{T_1}
-
\dfrac{T_{AL}}{T_L}
\right)
+
\exp
\left(
\dfrac{T_{AH}}{T_H}
-
\dfrac{T_{AH}}{T_1}
\right)
}
{
1 +
\exp
\left(
\dfrac{T_{AL}}{T}
-
\dfrac{T_{AL}}{T_L}
\right)
+
\exp
\left(
\dfrac{T_{AH}}{T_H}
-
\dfrac{T_{AH}}{T}
\right)
}
\right]
$$ {#eq-deb-temp}

If the particle is an embryo ($E_H < E_{Hb}$), then it does not feed. Please note that, according to this definition, a larva that hatched but does not feed is considered an embryo in DEB theory. Else, the scaled functional response $f$ is computed as:

$$
f = \dfrac{F}{F + K}
$$ {#eq-deb-repfonct}

with $F$ the food vector and $K$ the half-saturation constant.

Assimilation rates $\{\dot{p_{Am}}\}$, energy conductance $\dot{v}$, volume specific somatic maintenance ($[\dot{p}_M]$) and maturity maintenances rates ($\dot{k}_J$) are corrected by the $c_T$ factor.

If the accelerated DEB model is used (see e.g. @KOOIJMAN2011 and @KOOIJMAN2014 for more details), the acceleration factor is computed as follows

$$
s_M =
\begin{cases}
 1 & (E < E_{Hb})\\
 \dfrac{V^{1/3}}{L_b} & (E_{Hb} \le E_H < E_{Hj}) \\
 \dfrac{L_j}{L_b} & (E_{H} > E_{Hj})
\end{cases}
$$ {#eq-deb-sm}

with $L_b$ the structural length of the particle when $E_H = E_Hb$ (i.e the length at birth, i.e. first feeding) and $L_j$ the structural length of the particle when $E_H = E_Hj$ (i.e the length when metamorphosis occurs).

::: {.callout-warning}
The $L_b$ and $L_j$ values are computed by Ichthyop when the different stages are reached.

**Laure and Eline, does it seem ok?**

:::

The $s_M$ factor is then used to multiply the assimilation rate $\{\dot{p_{Am}}\}$ and the energy conductance $\dot{v}$.

<!-- (NICOLAS: s'agit il de la longueur structurelle $L = V^{1/3}$ ou de la longueur mesurée $L_w = L / \delta_M$). Please note that $L_b$ and $L_j$ are here considered as parameters but they should be in fact calculated prior any Ichthyop runs at (e.g. at $f = 1$) as they depend on the other parameters. If you are considering testing different parameter sets, $L_b$ and $L_j$ should be modified accordingly (e.g. using the DEBtool function `get_tj.m`). -->

Consequently, the assimilation (in $J.d^{-1}$) is computed as follows:

$$
\dot{p}_A = \begin{cases}
0 & (E_{H} < E_{Hb}) \\
 c_T s_M f \{ \dot{p}_{Am}\}  V^{2/3}  & (E_{H} \ge E_{Hb}) \\
\end{cases}
$$ {#eq-deb-pA}


Energy loss to maintenance is given by

$$
\dot{p}_M = c_T [ \dot{p}_M ]  V
$$ {#eq-deb-pM}

The mobilized energy is given by:

$$
\dot{p_C} = c_T
\dfrac{\dfrac{E}{V} \left([E_G]  s_M \dot{v} V^{2/3} + [\dot{p}_M]\right)}
{\kappa \dfrac{E}{V} + [E_G]}
$$ {#eq-deb-pC}

Maturity maintenance is given by

$$
\dot{p}_J = c_T \dot{k}_J E_H
$$ {#eq-deb-pJ}

Energy that is sent to structural growth is given by:

$$
\dot{p}_G = \kappa \dot{p}_C - \dot{p}_M
$$ {#eq-deb-pG}

Energy that goes to development (as embryo and juvenile) or to reproduction (as adults) is given by:

$$
\dot{p}_R = (1 - \kappa) \dot{p}_C - \dot{p}_J
$$ {#eq-deb-pR}

Finally, the increment of reserve $E$ and structural volume $V$ is given by:

$$
\dfrac{dE}{dt} = \dot{p}_A - \dot{p}_C
$$ {#eq-deb-dEdt}

$$
\dfrac{dV}{dt} = \dfrac{\dot{p}_G}{{[E_G]}}
$$  {#eq-deb-dVdt}

The increment of the energy invested into development or reproduction depends on the value of $E_H$.

$$
\dfrac{dE_H}{dt} =
\begin{cases}
\dot{p}_R & E_H < E_{Hp}\\
0 &  \text{otherwise}
\end{cases}
$$ {#eq-deb-dHdt}

$$
\dfrac{dE_R}{dt} =
\begin{cases}
0 & E_H < E_{Hp}\\
\dot{p}_R &  \text{otherwise}
\end{cases}
$$ {#eq-deb-dRdt}


Finally, starvation mortality is determined whether one of the following conditions are matched:

$$
M_{starv} =
\begin{cases}
\kappa \dot{p}_C  <  \dot{p}_M\\
(1 - \kappa) \dot{p}_C  <  \dot{p}_J
\end{cases}
$$ {#eq-deb-starv}

Finally, all the states variables are then incremented:

$$
E(t + \Delta t) = E(t) + \dfrac{dE}{dt}\Delta t
$$ {#eq-deb-incr-e}

$$
V(t + \Delta t) = V(t) + \dfrac{dV}{dt}\Delta t
$$ {#eq-deb-incr-v}

$$
E_H(t + \Delta t) = E_H(t) + \dfrac{dE_H}{dt}\Delta t
$$ {#eq-deb-incr-h}

$$
E_R(t + \Delta t) = E_R(t) + \dfrac{dE_R}{dt}\Delta t
$$ {#eq-deb-incr-r}
