

## Growth {#sec-growth-proc}

There is 2 different implementations of the growth module. They can be selected by setting the
`class_name` parameter in the `action.growth` action configuration block.

### Linear growth

To use the linear growth method described in @LETT20081210, choose the `LinearGrowthAction.java` class. Length depends on temperature but may
also depend on the available food if the `growth.food.enabled` parameter is set to True.

If food dependence is enabled, length increment is provided as follows:

$$
\Delta L = C1 + C2 \times \dfrac{F}{F + K_S} \times max(T, T_{thres}) \times \Delta t
$$

where $\Delta t$ is the time-step (in days), $C1$ and $C2$ are parameters (`coeff1` and `coeff2`), $T_{thres}$ is a temperature threshold (`threshold_temp` parameter), $F$ is the food quantity (read from the hydrodynamical dataset),  and $K_S$ is
a half-saturation constant (`half_saturation` parameter) and $T$ is the temperature.

If food dependence is disabled, then increment is provided as follows:

$$
\Delta L = C1 + C2 \times max(T, T_{thres}) \times \Delta t
$$

The name of the food and temperature variables are provided by the `food_field` and `temperature_field` parameters.

The initial length of the particle is provided by the `initial_length` parameter.

### Sole growth

If the {samp}`SoleGrowthAction.java` class is selected, the growth model used in @TANNER201778 is
used. It relies on the growth equation from @fonds1979laboratory and given by:

$$
\Delta L = C_1 \times T^{C_2} \times \Delta t
$$

with $L$ the length, $T$ the temperature and $\Delta t$ the time step in days, and $C_1$ and $C_2$ are parameters (`c1` and `c2` respectively).

The temperature field is provided by the `temperature_field` parameter.

### Exponential growth

If the `ExponentialGrowthAction.java` class is selected, the growth model used is exponential.

We assume that the length is given by the following equation:

$$
L(t) = L_0 \times \exp{\left(b T^c t\right)}
$$

with $L_0$ the initial length (in cm), $b$ the growth rate and $c$ the temperature dependence of the growth rate.

Taking the derivative of this expression, we obtain the increase in length as a function of time:

$$
\Delta L = L \times b \times T^{c} \times \Delta t
$$

The initial length of the particle is provided by the `initial_length` parameter.