## Lethal temperature and salinity

In Ichthyop, there is the possibility to define a range of temperature and salinity beyond which the particle is killed.

The same set of parameters are used in both cases, with the `temperature` and `salinity` prefix.
There are two ways to define lethal temperatures and salinities:

- Using constant lethal temperatures or salinities (if `temperature.file.enabled` or `salinity.file.enabled` is set to false)
- Using a CSV file containing lethal temperatures or salinities as a function of the particle class.

If constant lethal temperatures or salinities are provided, the cold and warm lethal temperatures
are provided with the `cold_lethal_temperature`, `warm_lethal_temperature`, `fresh_lethal_salinity`, `saline_lethal_salinity`,  .

If a CSV file is used, the lethal temperatures and salinities are provided in a CSV (`lethal_temperature_file` and `lethal_salinity_file` parameters) which is formatted as follows:

```bash
Age(days);Cold temperature (C);Warm temperature (C)
0;14;22
2;13;22
6;12;22
```

The first column provides the class intervals, which are either the age of the
particle (in days) or the length of the particle (in cm). The variable that is
used to determine the class is provided by the `temperature.class` parameter.