
## Zone configuration file {#sec-zone-xml-config}

Zone configuration files are also managed via a dedicated XML files. These files must be as follows:

```XML
<?xml version="1.0" encoding="UTF-8"?>
<zones>

</zones>
```

Each zone is defined into a `<zone>` tag, which contain the following tags:

- `<key>` is the name of the zone
- `<enabled>` specifies whether this zone must be activated by default or not.
- `<type>` specifies whether the zone should be used for release (`release` value, see @sec-zone-release) or recruitment (`recruitment` value)
- `<polygon>` specifies the different points used to define the zond area
- `<bathy_mask>` (optional) specifies a subset of zone area based on bathymetry (for example 0 to 200m, for using only the subset of zone area from 0 to 200 m depth)
- `<thickness>` (optional) specifies the upper and lower depths subsets of zone areas (**only valid for 3D runs**).
- `<color>` specifies the display color of the zone (format is `[r=102,g=51,b=255]`).
- `<proportion_particles>` (optional) specifies the percentage of total particles  (values in $[0-1]$) to be released in the area. This attribute is only used when `type` is `release` and if the `user_defined_nparticles` parameter is set to True (cf. @sec-zone-release)

::: {.callout-warning}

The sum of the values of `proportion_particles` over all the release zones should be 1!

:::

An example of a zone definition is provided below.

```XML
<zone>
    <key>Release zone 2</key>
    <enabled>true</enabled>
    <type>release</type>
    <polygon>
        <point>
            <index>0</index>
            <lon>54.0</lon>
            <lat>-11.5</lat>
        </point>
        <point>
            <index>1</index>
            <lon>54.0</lon>
            <lat>-12.5</lat>
        </point>
        <point>
            <index>2</index>
            <lon>53.0</lon>
            <lat>-12.5</lat>
        </point>
        <point>
            <index>3</index>
            <lon>53.0</lon>
            <lat>-11.5</lat>
        </point>
    </polygon>
    <bathy_mask>
        <enabled>true</enabled>
        <line_inshore>0.0</line_inshore>
        <line_offshore>12000.0</line_offshore>
    </bathy_mask>
    <thickness>
        <enabled>true</enabled>
        <upper_depth>0.0</upper_depth>
        <lower_depth>50.0</lower_depth>
        </thickness>
    <color>[r=102,g=51,b=255]</color>
    <proportion_particles>0.2</proportion_particles>
</zone>
```
