/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.previmer.ichthyop.ui;

/**
 *
 * @author barrier
 */
public class GridSelectionPanel extends javax.swing.JDialog {

    /**
     * Creates new form GridSelectionPanel
     */
    public GridSelectionPanel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        romsButton = new javax.swing.JButton();
        marsButton = new javax.swing.JButton();
        regularButton = new javax.swing.JButton();
        nemoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose a grid template");
        setResizable(false);
        setSize(new java.awt.Dimension(500, 200));

        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        romsButton.setText("ROMS");
        romsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                romsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(romsButton);

        marsButton.setText("MARS");
        marsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(marsButton);

        regularButton.setText("REGULAR");
        regularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regularButtonActionPerformed(evt);
            }
        });
        jPanel1.add(regularButton);

        nemoButton.setText("NEMO");
        nemoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nemoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nemoButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nemoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nemoButtonActionPerformed
        // TODO add your handling code here:
        this.genericButtonActionPerformed(evt);
    }//GEN-LAST:event_nemoButtonActionPerformed

    private void marsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marsButtonActionPerformed
        // TODO add your handling code here:
        this.genericButtonActionPerformed(evt);
    }//GEN-LAST:event_marsButtonActionPerformed

    private void romsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_romsButtonActionPerformed
        // TODO add your handling code here:
        this.genericButtonActionPerformed(evt);
    }//GEN-LAST:event_romsButtonActionPerformed

    private void regularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regularButtonActionPerformed
        // TODO add your handling code here:
        this.genericButtonActionPerformed(evt);
    }//GEN-LAST:event_regularButtonActionPerformed
    
    private void genericButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Object source = evt.getSource();
        if (source == nemoButton) {
            this.chosenGrid = "nemo";
        }
        else if (source == marsButton) {
            this.chosenGrid = "mars";
        }
        else if (source == romsButton) {
            this.chosenGrid = "roms";
        }
        else if (source == regularButton) {
            this.chosenGrid = "regular";
        }
        else { 
            this.chosenGrid = null;
        }
        
        this.setVisible(false);

    }
    public String getChosenGrid() {
        return this.chosenGrid.toUpperCase();    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GridSelectionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GridSelectionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GridSelectionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GridSelectionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GridSelectionPanel dialog = new GridSelectionPanel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton marsButton;
    private javax.swing.JButton nemoButton;
    private javax.swing.JButton regularButton;
    private javax.swing.JButton romsButton;
    // End of variables declaration//GEN-END:variables
    private String chosenGrid;
}
