## Interpolation of coordinates

There are two coordinate systems in Ichthyop:

-   the grid coordinate, with `x` ranging from 0 to `nx - 1` and `y` ranging from `0` to `ny - 1`
-   the geographical coordinates, i.e. longitude and latitude

In Ichthyop, there are fonctions that allows to switch from one system to another, considering that the grid may be irregular (for example NEMO or CROCO grid).

### Grid to geographical coordinates

Conversion from grid to geographical coordinates is done by using the `xy2latlon` methods associated with `Dataset` objects.

This function is a bilinear interpolation of the grid coordinates, as shown in @fig-xy2latlon

```{python}
#| echo: false
#| output: true
#| label: fig-xy2latlon
import matplotlib.pyplot as plt
import numpy as np

plt.figure()

x = [0, 1, 1, 0, 0]
y = [0, 0, 1, 1, 0]

xp = 0.3
yp = 0.6

arrowprops = dict(facecolor='black', arrowstyle='<->')

plt.plot(x, y)
plt.annotate('(i, j)', (0, -0.05), va='top', ha='center')
plt.annotate('(i+1, j)', (1, -0.05), va='top', ha='center')
plt.annotate('(i, j+1)', (0, 1 + 0.05), va='bottom', ha='center')
plt.annotate('(i+1, j+1)', (1, 1 + 0.05), va='bottom', ha='center')

plt.plot(xp, yp, marker='o')
plt.annotate('P', (xp, yp + 0.01), ha='left', va='bottom')

plt.annotate('', (xp, 0), xytext=(0, 0), arrowprops=arrowprops,)
plt.annotate('dx', (xp / 2, -0.01), ha='center', va='top')

plt.annotate('', (0, yp), xytext=(0, 0), arrowprops=arrowprops,)
plt.annotate('dy', (0-0.01, yp / 2), ha='right', va='center')

plt.annotate('', (0, yp), xytext=(0, 1), arrowprops=arrowprops,)
plt.annotate('1 - dy', (0-0.01, yp + (1 - yp) / 2), ha='right', va='center')

plt.annotate('', (xp, 0), xytext=(1, 0), arrowprops=arrowprops,)
plt.annotate('1 - dx', (xp + (1 - xp) / 2, 0-0.01, ), ha='center', va='top')

plt.plot([0, 1], [yp, yp], ls='--', lw=0.5)
plt.plot([xp, xp], [0, 1], ls='--', lw=0.5)

plt.axis('off')
offset = 0.2
plt.ylim(-offset, 1 + offset)
plt.xlim(-offset, 1 + offset)
plt.show()
```

The coordinate of the particle P is determined as a weighted mean of the coordinates of the four corners, with the weight being provided by the distance of the particle from the corners (`dx` `dy`). The closest the particle is to a corner, the more weight is has.

For example, the longitude of the particle $lambda_P$ is given by:

$$
\lambda_P =  (1 - dx)(1-dy) \lambda_(i, j) +
dx(1-dy) \lambda_(i + 1, j) +
(1 - dx)dy \lambda_(i, j+1) +
dxdy \lambda_(i+1, j+1)
$$

Note that by construction, the sum of the weight equals to 1, so no need to divide by the total weight.

### Geographical to grid coordinates

The switch from geographical to grid coordinates is a bit more tricky, considering that the grid may be irregular. Let's consider the example in @fig-latlon2xy

The first step is to determine the coordinates of the cell in wich the particle is located. In the code, this is done by a dichotomic search. We first look in which quarter of the domain the particle is located. This quarter is then decomposed into 4 quarters, and we determine in which subquarter the particle is locate. At the end, the cell in which the particle is located is selected (@fig-latlon2xy).

```{python}
#| echo: false
#| output: true
#| label: fig-latlon2xy
lonO = 43
latO = 5

lonA = 46
latA = 7

lonB = 42
latB = 8

lonC = 41
latC = 6

lonP = 1 / 4. * (lonB + lonA + lonO + lonC)
latP = 1 / 4. * (latB + latA + latO + latC)

plt.plot([lonO, lonA, lonB, lonC, lonO], [latO, latA, latB, latC, latO])
plt.plot([lonO], latO, marker='o', label='O')
plt.plot([lonA], latA, marker='o', label='A')
plt.plot([lonB], latB, marker='o', label='B')
plt.plot([lonC], latC, marker='o', label='C')
plt.plot([lonP], latP, marker='o', label='P')

# Coordonnees pour tracer les droites
x = np.linspace(41, 46, 20)

# tracer d'une droite en s'appuyant sur un invariant
dy = latC - latO
dx = lonC - lonO
c = lonP * dy - latP * dx
y = (x*dy -c) / dx
plt.plot(x, y, ls='--')

# tracer d'une droite en s'appuyant sur un invariant
dy = latA - latO
dx = lonA - lonO
c = lonP * dy - latP * dx
y = (x*dy -c) / dx
plt.plot(x, y , ls='--')

# Calcul de l'intersection en coordoonnes
dy1 = latC - latO
dx1 = lonC - lonO
dy2 = latA - latO
dx2 = lonA - lonO
c1 = lonP * dy1 - latP * dx1 # droite c1 qui passe par P et parallele a OC
c2 = lonO * dy2 - latO * dx2 # droite c2 = droite OA
D = (dx2 * dy1 - dy2 * dx1)
lonI = (c1 * dx2 - c2 * dx1) / D
latI = -(c2 * dy1 - c1 * dy2) / D
deltax1 = (lonI - lonO) / (lonA - lonO)

plt.plot(lonI, latI, marker='o')

# Calcul de l'intersection en coordoonnes
dy2 = latC - latO
dx2 = lonC - lonO
dy1 = latA - latO
dx1 = lonA - lonO
c1 = lonP * dy1 - latP * dx1 # droite c1 qui passe par P et parallele a OC
c2 = lonO * dy2 - latO * dx2 # droite c2 = droite OA
D = (dx2 * dy1 - dy2 * dx1)
lonJ = (c1 * dx2 - c2 * dx1) / D
latJ = -(c2 * dy1 - c1 * dy2) / D

plt.plot(lonJ, latJ, marker='o')
deltay1 = (latJ - latO) / (latC - latO)

# Resolution reelle de dx sans passer par les coordonnes
D = (lonA - lonO) * (latC - latO) - (latA - latO) * (lonC - lonO)
Dx = (lonP - lonO) * (latC - latO) - (latP - latO) * (lonC - lonO)
Dy = (lonA - lonO) * (latP - latO) - (latA - latO) * (lonP - lonO)

deltax2 = Dx / D
deltay2 = Dy / D

print(deltax1, deltax2)
print(deltay1, deltay2)

plt.axis('equal')
plt.legend()

```

Each corner of the cell is given by a longitude and latitude $\lambda_{i,j}, \phi_{i,j}$, while the particle has longitude and latitude given by $\lambda_{P}, \phi_{P}$. The objective is to determine, given the geographical coordinates of the coordinates and of the particle, the $\Delta x$ and $\Delta y$ values of the particle, so that:

$$
x_P = i + \Delta x
$$

$$
y_P = j + \Delta y
$$

with $(x_P, y_P)$ the particle grid coordinate and $(i,j)$ the coordinate of the lower left corner.

We assume that:

$$
\mathbf{OP} = A \times  \mathbf{OA} + B \times \mathbf{OC}
$$

When using the geographical coordinates:

$$
\lambda_P - \lambda_O = \Delta X \times (\lambda_A - \lambda_O) + \Delta y \times  (\lambda_C - \lambda_O)
$$ #eq-lambda-p

and

$$
\phi_P - \phi_O = \Delta X \times (\phi_A - \phi_O) + \Delta y  \times (\phi_C - \phi_O)
$$  #eq-phi-p

This is a system of 2 equations with two unknown ($\Delta X$ and $\Delta y$). It is not resolved directly. Instead, we will look for the value of the longitude of the intersect of the straight line that crosses P and which is perpendicular to $\mathbf{OC}$ with the straight line $\mathbf{OA}$.

Based on the fact that each point $(X, Y)$ belonging to a straight line width a slope $(S_y, S_x)$, we have:

$$
X \times S_y - Y \times S_x = c
$$

with $c$ a constant, we can characterise these two straight lines with the known coordinates:

$$
\phi_P (\lambda_C - \lambda_O) - \lambda_P (\phi_C - \phi_O) = c1
$$

which characterize the line that crosses P and that is parallel to OC

$$
\phi_O (\lambda_A - \lambda_O) - \lambda_O (\phi_A - \phi_O) = c2
$$

which characterize the OA line.

Since the unknown point also is on these two lines, we can write

$$
\phi_I (\lambda_C - \lambda_O) - \lambda_I (\phi_C - \phi_O) = c1
$$

$$
\phi_I (\lambda_A - \lambda_O) - \lambda_I (\phi_A - \phi_O) = c2
$$

This is an equation with two unknown ($\phi_I$ and $\lambda_I$) that can be solved using the Cramer formula. In this case, we are only interested in $\lambda I$:

$$
\lambda_I =
\frac{
c_2(\lambda_C-\lambda_O)-c_1(\lambda_A-\lambda_O)
}{
(\lambda_A-\lambda_O)(\phi_C-\phi_O)
-(\lambda_C-\lambda_O)(\phi_A-\phi_O)
}
$$

Finally, the grid increment is given as follows:

$$
\Delta x = \frac{(\lambda_I - \lambda_O)}{(\lambda_I - \lambda_A)}
$$

The same operation is done to determine the latitude of $\phi_J$ and hence the $\Delta y$ grid increment.

::: {.callout-caution}

Since the grid is irregular, the cell edges may not be orthogonal. Therefore, a simple projection does not work

:::

::: {.callout-note}

The equation could be resolved more easily using @eq-lambda-p and @eq-phi-p, also using Cramer's formula:

$$
D = (lonA - lonO)(latC - latO) - (latA - latO)(lonC-lonO)
$$

$$
D_x = (lonP - lonO)(latC - latO) - (lonC - lonO) (latP - latO)
$$

$$
D_y = (lonA - lonO)(latP - latO) - (latA - latO) (lonP - lonO)
$$

$$
\Delta x = \dfrac{D_x}{D}
$$

$$
\Delta y = \dfrac{D_x}{D}
$$