# Simple workflow for deploying static content to GitHub Pages
name: Build Ichthyop Documentation

on:
    push:
        branches: ["release/*", "master"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
            GH_TOKEN: ${{ secrets.GH_GITHUB_COM_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Cache Input Files
        id: cache-input
        uses: actions/cache@v3
        env:
            cache-name: cache-input-files
        with:
            path: input
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('input/*.nc') }}
            restore-keys: |
                ${{ runner.os }}-build-${{ env.cache-name }}-
                ${{ runner.os }}-build-
                ${{ runner.os }}-

      - name: Update apt
        run:  sudo apt update -yq

      - name: Install Python
        run:  sudo apt install python3 pip python-is-python3 maven openjdk-21-jdk

      - name: Download input files
        if: steps.cache-input.outputs.cache-hit != 'true'
        run: wget https://zenodo.org/records/10890690/files/input.zip && unzip input.zip

      - name: Install Packages
        run:  pip install cartopy matplotlib numpy nbformat jupyter-cache netcdf4 jupytext ipykernel xarray pandas dask scipy

      - name: Build png maps
        run: cd doc && quarto render

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'doc/_book'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
