# This is a basic workflow to help you get started with Actions

name: java-build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push


jobs:
  # This workflow contains a single job called "build"
  java-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install OS dependencies and CA certificates
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates ca-certificates-java libnetcdf-dev

      - name: Cache Maven dependencies
        id: maven-dep
        uses: actions/cache@v3
        env:
            cache-name: maven-dep-modules
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.jar') }}

      - name: Cache Input Files
        id: cache-input
        uses: actions/cache@v3
        env:
            cache-name: cache-input-files
        with:
            path: input
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('input/*.nc') }}

      - name: Download java files
        if: steps.cache-input.outputs.cache-hit != 'true'
        run: wget https://zenodo.org/records/10890690/files/input.zip

      - name: Unzip input files
        if: steps.cache-input.outputs.cache-hit != 'true'
        run: unzip input.zip

      - name: Compile Java code
        run: |
          mvn -B clean package -DskipTests=true
